"""Extract data relevant to TWAS hits of interest to plot as examples

- Mean binned coverage and high vs. low sample mean coverage for the gene
- TWAS weights for the phenotype to plot alongside GWAS z-scores
- GWAS sumstat z-scores within the gene range
"""

import os
import pandas as pd

phenos = pd.read_csv('example_phenos_all.tsv', sep='\t')
ids = phenos.phenotype_id.tolist()
genes = phenos.gene_id.unique().tolist()
gene_tissue_pairs = [f'{row["gene_id"]}.{row["tissue"]}' for _, row in phenos.iterrows()]
id_tissue_pairs = [f'{row["phenotype_id"]}.{row["tissue"]}' for _, row in phenos.iterrows()]
trait_gene_pairs = [f'{row["trait"]}-{row["gene_id"]}' for _, row in phenos.iterrows()]
tissues = sorted(phenos.tissue.unique().tolist())

gene_info = pd.read_csv('../phenos/gtextcga-full/info/genes.tsv', sep='\t')
gene_info = gene_info[gene_info.gene_id.isin(genes)]
gene_chrom = dict(zip(gene_info.gene_id, gene_info.seqname))
pheno_chrom = {row.phenotype_id: gene_chrom[row.gene_id] for _, row in phenos.iterrows()}
tqtl_script = os.path.expanduser('~/tools/Pantry/pheast/scripts/run_tensorqtl.py')
gtex_geno_prefix = '/data/hps/home/dmunro/gdml/pantry/GTEx/geno/gtex'

localrules:
    copy_model_info,
    copy_weights,
    gwas_sumstats,

rule all:
    input:
        expand('model_info/inspect.{gene_tissue}.tsv.gz', gene_tissue=gene_tissue_pairs),
        expand('weights/{pheno_tissue}.wgt.RDat', pheno_tissue=id_tissue_pairs),
        expand('gwas/{trait_gene}.tsv.gz', zip, trait_gene=trait_gene_pairs),
        expand('cis_nominal/{pheno_tissue}.tsv.gz', pheno_tissue=id_tissue_pairs[-1]),

rule get_model_info:
    input:
        phenos = '../phenos/gtextcga-full/phenotypes/latent_phenos.{tissue}.tsv.gz',
    output:
        tsv = '../phenos/gtextcga-full/inspect/inspect.{gene}.{tissue}.tsv.gz',
    params:
        pheno_dir = '../phenos/gtextcga-full/',
    shell:
        'laddr inspect -p {params.pheno_dir} -d {wildcards.tissue} -g {wildcards.gene}'

rule copy_model_info:
    input:
        tsv = '../phenos/gtextcga-full/inspect/inspect.{gene}.{tissue}.tsv.gz',
    output:
        tsv = 'model_info/inspect.{gene}.{tissue}.tsv.gz',
    shell:
        'cp {input.tsv} {output.tsv}'

rule copy_weights:
    input:
        wgt = '../pheast/gtextcga-full/intermediate/twas/{tissue}-latent/{id}.wgt.RDat',
    output:
        wgt = 'weights/{id}.{tissue}.wgt.RDat',
    shell:
        'cp {input.wgt} {output.wgt}'

rule gwas_sumstats:
    input:
        gwas = '../../data/gwas/imputed_gwas_hg38_1.1/imputed_{trait}.txt.gz',
    output:
        tsv = 'gwas/{trait}-{gene}.tsv.gz',
    params:
        chrom = lambda w: gene_info.seqname[gene_info.gene_id == w.gene].values[0],
        start = lambda w: gene_info.tss[gene_info.gene_id == w.gene].values[0] - 500000,
        end = lambda w: gene_info.tss[gene_info.gene_id == w.gene].values[0] + 500000,
    shell:
        """
        zcat {input.gwas} \
            | awk -v chrom={params.chrom} -v start={params.start} -v end={params.end} 'NR==1 || ($3 == chrom && $4 >= start && $4 <= end)' \
            | gzip -c \
            > {output.tsv}
    """

rule make_pheno_bed:
    input:
        bed = '../pheast/gtextcga-full/input/phenotypes/{tissue}-latent.bed.gz',
        bedi = '../pheast/gtextcga-full/input/phenotypes/{tissue}-latent.bed.gz.tbi',
    output:
        bed = 'cis_nominal/phenos/{phenotype_id}.{tissue}.bed.gz',
        tbi = 'cis_nominal/phenos/{phenotype_id}.{tissue}.bed.gz.tbi',
    conda: 'pheast'
    params:
        phenotype_id = '{phenotype_id}',
    shell:
        """
        mkdir -p cis_nominal/phenos
        zcat {input.bed} \
            | awk -v pheno="{params.phenotype_id}" 'NR==1 || $4 == pheno' \
            | bgzip -c \
            > {output.bed}
        tabix -p bed {output.bed}
        """

rule tensorqtl_cis_nominal:
    input:
        geno = multiext(gtex_geno_prefix, '.bed', '.bim', '.fam'),
        bed = 'cis_nominal/phenos/{phenotype_id}.{tissue}.bed.gz',
        bedi = 'cis_nominal/phenos/{phenotype_id}.{tissue}.bed.gz.tbi',
        covar = '../pheast/gtextcga-full/intermediate/covar/{tissue}-latent.covar.tsv',
    output:
        nominal = 'cis_nominal/{phenotype_id}.{tissue}/{phenotype_id}.{tissue}.cis_qtl_pairs.chr{chrom}.parquet'
    params:
        output_prefix = '{phenotype_id}.{tissue}',
        output_dir = 'cis_nominal/{phenotype_id}.{tissue}',
        script = tqtl_script,
    conda: 'pheast'
    resources:
        mem_mb = 32000,
    shell:
        """
        mkdir -p {params.output_dir}
        python3 {params.script} \
            {gtex_geno_prefix} \
            {input.bed} \
            {params.output_prefix} \
            --covariates {input.covar} \
            --output_dir {params.output_dir} \
            --mode cis_nominal
        """

rule extract_cis_nominal_pheno:
    input:
        nominal = lambda w: f'cis_nominal/{w.phenotype_id}.{w.tissue}/{w.phenotype_id}.{w.tissue}.cis_qtl_pairs.{pheno_chrom[w.phenotype_id]}.parquet',
    output:
        tsv = 'cis_nominal/{phenotype_id}.{tissue}.tsv.gz',
    run:
        from fastparquet import ParquetFile

        df = ParquetFile(input.nominal).to_pandas()
        df = df.loc[df["phenotype_id"] == wildcards.phenotype_id]
        df.to_csv(output.tsv, sep="\t", index=False, float_format="%g", compression="gzip")
