## Point to the Pantry output directory containing BED files:
# phenotype_dir: ../Project/output
# Since the tables produced by the main test dataset may be too small for
# downstream analyses, the Pheast tests use another test dataset produced by
# Pheast/scripts/test_prepare_data.sh:
phenotype_dir: input/phenotypes

## Give the path prefix to genotypes in plink1 (bed/bim/fam) format:
geno_prefix: ../../../pantry/GTEx/geno/gtex

## Samples to include:
samples_file: input/samples.txt

## Optional parameters
# Provide a list of SNP IDs to include when computing TWAS weights:
# It is recommended to include only SNPs present in the LD reference used later for TWAS.
twas_snps: ../../../pantry/GTEx/geno/LD_SNPs.txt
# Path to intermediate file directory, in case you don't want it inside this project directory due to its size:
# This directory will be created if it doesn't exist, and will contain any generated (i.e. not input) files besides the final analysis results.
# intermediate_dir: intermediate

## Modalities
# List the modalities to use. The phenotype table ({modality}.bed.gz)
# must be present in the phenotype_dir, along with a
# {modality}.phenotype_groups.txt file in the case of grouped phenotypes.
# 'cross_modality' is used to run cross-modality QTL mapping. See Project/scripts/combine_modalities.sh for more details.
modalities:
  latent-0:
    grouped: true
  latent-20:
    grouped: true
  latent-40:
    grouped: true
  latent-60:
    grouped: true
  latent-80:
    grouped: true
  latent-100:
    grouped: true
  pantry-0:
    grouped: true
  pantry-20:
    grouped: true
  pantry-40:
    grouped: true
  pantry-60:
    grouped: true
  pantry-80:
    grouped: true
  pantry-100:
    grouped: true
  alt_polyA-20:
    grouped: true
  alt_polyA-40:
    grouped: true
  alt_polyA-60:
    grouped: true
  alt_polyA-80:
    grouped: true
  alt_polyA-100:
    grouped: true
  alt_TSS-20:
    grouped: true
  alt_TSS-40:
    grouped: true
  alt_TSS-60:
    grouped: true
  alt_TSS-80:
    grouped: true
  alt_TSS-100:
    grouped: true
  expression-0:
    grouped: false
  expression-20:
    grouped: false
  expression-40:
    grouped: false
  expression-60:
    grouped: false
  expression-80:
    grouped: false
  expression-100:
    grouped: false
  isoforms-20:
    grouped: true
  isoforms-40:
    grouped: true
  isoforms-60:
    grouped: true
  isoforms-80:
    grouped: true
  isoforms-100:
    grouped: true
  splicing-0:
    grouped: true
  splicing-20:
    grouped: true
  splicing-40:
    grouped: true
  splicing-60:
    grouped: true
  splicing-80:
    grouped: true
  splicing-100:
    grouped: true
  stability-0:
    grouped: false
  stability-20:
    grouped: false
  stability-40:
    grouped: false
  stability-60:
    grouped: false
  stability-80:
    grouped: false
  stability-100:
    grouped: false

## Analyses
# List the analyses to run. A snakefile will be loaded for each analysis,
# steps/{analysis}.smk, and results will be written to output/{analysis}/.
# {modality} will be replaced with each modality name.
analyses:
  # heritability:
  #   files:
  #   - '{modality}.hsq.tsv'
  qtl:
    files:
    - '{modality}.cis_qtl.txt.gz'
    - '{modality}.cis_independent_qtl.txt.gz'
    # - '{modality}.trans_qtl.txt.gz'
  # twas:
  #   files:
  #   - '{modality}.tar.bz2'
