"""Process latent phenotyping output for held-out runs and set up for Pheast"""

# Use GTF without gene ID versions
ref_anno='../../ref/human-ensembl/Homo_sapiens.GRCh38.113.chr.chrom.gtf'
modalities = ['alt_polyA', 'alt_TSS', 'expression', 'isoforms', 'splicing', 'stability']

localrules:
    index_bed,

rule all:
    input:
        expand('qtl/input/phenotypes/cross-no_{modality}.bed.gz.tbi', modality=modalities),
        expand('qtl/input/phenotypes/cross-no_{modality}.phenotype_groups.txt', modality=modalities),

rule assemble_latent_bed:
    """Add gene info to latent phenotypes to generate BED file"""
    input:
        phenos = 'no_{modality}/phenotypes/latent_phenos.Geuvadis.tsv.gz',
        ref_anno = ref_anno,
    output:
        bed = 'qtl/input/phenotypes/unnorm/latent-no_{modality}.unnorm.bed',
    resources:
        mem_mb = 32000,
    shell:
        """
        python3 ~/tools/Pantry/phenotyping/scripts/assemble_bed.py \
            --type latent \
            --input {input.phenos} \
            --ref_anno {input.ref_anno} \
            --output {output.bed}
        """

rule normalize_latent:
    """Quantile-normalize values for QTL mapping"""
    input:
        bed = 'qtl/input/phenotypes/unnorm/latent-no_{modality}.unnorm.bed',
    output:
        bed = 'qtl/input/phenotypes/latent-no_{modality}.bed.gz',
    params:
        bed = 'qtl/input/phenotypes/latent-no_{modality}.bed',
    resources:
        mem_mb = 32000,
    shell:
        """
        python3 ~/tools/Pantry/phenotyping/scripts/normalize_phenotypes.py \
            --input {input.bed} \
            --output {params.bed}
        bgzip {params.bed}
        """

def pantry_phenos_input(wildcards):
    mods = [m for m in modalities if m != wildcards.modality]
    assert len(mods) == len(modalities) - 1
    paths = expand('../data/geuvadis/pantry/output/{modality}.bed.gz', modality=mods)
    return paths

rule combine_modalities:
    """Combine latent and Pantry phenotypes"""
    input:
        pantry_phenos = pantry_phenos_input,
        latent_phenos = 'qtl/input/phenotypes/latent-no_{modality}.bed.gz',
    output:
        bed = 'qtl/input/phenotypes/cross-no_{modality}.bed.gz',
        groups = 'qtl/input/phenotypes/cross-no_{modality}.phenotype_groups.txt',
    params:
        tmp_dir = 'qtl/input/phenotypes/tmp_no_{modality}',
        modalities = lambda wildcards: [m for m in modalities if m != wildcards.modality],
    shell:
        """
        set -e
        mkdir {params.tmp_dir}
        mkdir {params.tmp_dir}/output
        ln -s ../../latent-no_{wildcards.modality}.bed.gz {params.tmp_dir}/output/latent_residual.bed.gz
        for modality in {params.modalities}; do
            ln -s ../../../../../../data/geuvadis/pantry/output/$modality.bed.gz {params.tmp_dir}/output/$modality.bed.gz
        done
        cd {params.tmp_dir}
        bash ~/tools/Pantry/phenotyping/scripts/combine_modalities.sh \
            {params.modalities} latent_residual
        cd -
        mv {params.tmp_dir}/output/cross_modality.bed.gz {output.bed}
        mv {params.tmp_dir}/output/cross_modality.phenotype_groups.txt {output.groups}
        rm -r {params.tmp_dir}
        """

rule index_bed:
    """Index a BED file."""
    input:
        bed = 'qtl/input/phenotypes/cross-no_{modality}.bed.gz',
    output:
        tbi = 'qtl/input/phenotypes/cross-no_{modality}.bed.gz.tbi'
    shell:
        'tabix {input.bed}'

