from pathlib import Path

DEFAULT_DIR = 'binning-n_4' # Directory to read universal files like n_batches.txt

BATCH_FILE = Path(f'{DEFAULT_DIR}/info/n_batches.txt')
assert BATCH_FILE.exists(), f'{BATCH_FILE} not found. Run latent-rna setup first.'
with open(BATCH_FILE, 'r') as f:
    N_BATCHES = int(f.read())

input_dir = Path('../data/input')
ref_genome = '../../pantry/Geuvadis/input/human_ref/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
## awk '$1 ~ /^#!/ || $1 == "7"' ../../pantry/Geuvadis/input/human_ref/Homo_sapiens.GRCh38.106.gtf > Homo_sapiens.GRCh38.106.chr7.gtf
ref_anno = 'Homo_sapiens.GRCh38.106.chr7.gtf'
bam_dir = input_dir / 'bam'
geno_prefix = '../../pantry/Geuvadis/input/genotype/GEUVADIS.445_samples.GRCh38.20170504.maf01.filtered.nodup.nochr.chr1-22'

binnings = []
for min_covg in [16, 32, 64, 128]:
    for max_corr in [0.8, 0.9, 0.95]:
        binnings.append(f'a1_{min_covg}_{max_corr}')
for bins_per_gene in [128, 256, 384, 512, 768, 1024]:
    binnings.append(f'a2_{bins_per_gene}')
for bins_per_gene in [128, 256, 384, 512, 768, 1024]:
    binnings.append(f'a3_{bins_per_gene}')
for n in [4, 8, 12, 16, 24, 32]:
    binnings.append(f'n_{n}')
for w in [16, 32, 64]:
    binnings.append(f'w_{w}_{w * 8}')

models = []
for n in [6, 8, 10, 12, 14, 16, 20, 24]:
    models.append(f'pca_n{n}')
models += ['fpca_xpos_disc', 'fpca_xpos_spline', 'fpca_xbin_spline']

params = [f'binning-{x}' for x in binnings] + [f'model-{x}' for x in models]

localrules:
    latent_pheno_groups,

rule all:
    input:
        # expand('binning-{binning}/gene_bins/batch_{batch}.bed.gz', binning=['n_4'], batch=range(N_BATCHES)),
        # expand('binning-{binning}/covg_norm/Geuvadis/batch_{batch}.npy', binning=['n_4'], batch=range(N_BATCHES)),
        # expand('{param}/models/models_batch_{batch}.pickle', param=['binning-n_4'], batch=range(N_BATCHES)),
        # expand('binning-{binning}/phenotypes/latent_phenos.Geuvadis.tsv.gz', binning=binnings),
        # expand('{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz', param=['binning-n_4']),
        # expand('qtl/latent-{param}.bed.gz', param=params),
        expand('qtl/latent-{param}.cis_independent_qtl.txt.gz', param=params),
        'bin_pheno_qtl_counts.tsv',

rule get_gene_bins:
    """Divide gene features into bins"""
    input:
        genes = '{param}/info/genes.tsv',
        exons = '{param}/info/exons.tsv.gz',
        # bw = sample_table['path'].tolist(),
    output:
        beds = '{param}/gene_bins/batch_{batch}.bed.gz',
    resources:
        mem_mb = 16000,
    shell:
        """
        latent-rna binning -p {wildcards.param} -b {wildcards.batch}
        """

rule prepare_coverage:
    """Assemble coverage across samples, normalize, regress out explicit phenotypes, and bin into batches for PCA"""
    input:
        # bw = lambda w: sample_table.loc[sample_table['dataset'] == w.dataset, 'path'].tolist(),
        bins = '{param}/gene_bins/batch_{batch}.bed.gz',
        # phenos = config['input']['pheno_paths'],
    output:
        covg = '{param}/covg_norm/Geuvadis/batch_{batch}.npy',
        bins = '{param}/covg_norm/Geuvadis/batch_{batch}.bins.tsv.gz',
    resources:
        walltime = 12,
    shell:
        """
        latent-rna coverage -p {wildcards.param} -b {wildcards.batch}
        """

rule fit_models:
    """Fit models to latent features"""
    input:
        covg_norm = '{param}/covg_norm/Geuvadis/batch_{batch}.npy',
        bins = '{param}/covg_norm/Geuvadis/batch_{batch}.bins.tsv.gz',
    output:
        models = '{param}/models/models_batch_{batch}.pickle',
    shell:
        """
        latent-rna fit -p {wildcards.param} -b {wildcards.batch}
        """

rule get_latent_phenotypes:
    """Apply models to generate latent phenotypes"""
    input:
        covg_norm = expand('{{param}}/covg_norm/Geuvadis/batch_{batch}.npy', batch=range(N_BATCHES)),
        models = expand('{{param}}/models/models_batch_{batch}.pickle', batch=range(N_BATCHES)),
    output:
        phenos = '{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz',
    shell:
        """
        latent-rna transform -p {wildcards.param}
        """

##################################
## Genetic analysis preparation ##
##################################

rule assemble_latent_bed:
    """Add gene info to latent phenotypes to generate BED file"""
    input:
        phenos = '{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz',
        ref_anno = ref_anno,
    output:
        bed = 'qtl/latent-{param}.unnorm.bed',
    params:
        qtl_dir = 'qtl',
    resources:
        mem_mb = 16000,
    shell:
        """
        mkdir -p {params.qtl_dir}
        python3 ~/tools/Pantry/Project/scripts/assemble_bed.py \
            --type latent \
            --input {input.phenos} \
            --ref_anno {input.ref_anno} \
            --output {output.bed}
        """

rule normalize_latent:
    """Quantile-normalize values for QTL mapping"""
    input:
        bed = 'qtl/latent-{param}.unnorm.bed',
        samples = input_dir / 'samples.txt',
    output:
        bed = 'qtl/latent-{param}.bed.gz',
    params:
        bed = 'qtl/latent-{param}.bed',
    resources:
        mem_mb = 16000,
    shell:
        """
        python3 ~/tools/Pantry/Project/scripts/normalize_phenotypes.py \
            --input {input.bed} \
            --samples {input.samples} \
            --output {params.bed}
        bgzip {params.bed}
        """

rule index_bed:
    """Index a BED file."""
    input:
        bed = 'qtl/latent-{param}.bed.gz',
    output:
        index = 'qtl/latent-{param}.bed.gz.tbi'
    shell:
        'tabix {input.bed}'


rule latent_pheno_groups:
    """Group phenotypes by gene for tensorQTL"""
    input:
        bed = 'qtl/latent-{param}.bed.gz',
    output:
        groups = 'qtl/latent-{param}.phenotype_groups.txt',
    shell:
        """
        zcat < {input} \
            | tail -n +2 \
            | cut -f4 \
            | awk '{{ g=$1; sub(/:.*$/, "", g); print $1 "\t" g }}' \
            > {output}
        """

rule prune_for_covar:
    """Prune genotypes to compute covariate PCs.
    --indep-pairwise parameters are based on GTEx methods.
    """
    input:
        plink = multiext(geno_prefix, '.bed', '.bim', '.fam'),
    output:
        vcf = 'covar/geno_pruned.vcf.gz',
    params:
        geno_prefix = geno_prefix,
        covar_dir = 'covar',
        pruned_prefix = 'covar/geno_pruned',
    shell:
        # --geno 0.05 filters variants with >5% missing values (the rest will be imputed).
        # Default is 0 so that samples with many more genotyped variants than others don't
        # result in other samples having mostly missing values after pruning.
        """
        mkdir -p {params.covar_dir}
        plink2 \
            --bfile {params.geno_prefix} \
            --geno 0.00 \
            --maf 0.05 \
            --indep-pairwise 200 100 0.1 \
            --out {params.pruned_prefix}
        plink2 \
            --bfile {params.geno_prefix} \
            --extract {params.pruned_prefix}.prune.in \
            --export vcf bgz id-paste=iid \
            --out {params.pruned_prefix}
        """

rule covariates:
    """Compute genotype and expression PCs and combine."""
    input:
        vcf = 'covar/geno_pruned.vcf.gz',
        bed = 'qtl/latent-{param}.bed.gz',
    output:
        tsv = 'covar/latent-{param}.covar.tsv',
    params:
        n_geno_pcs = 5,
        n_pheno_pcs = 20,
    resources:
        mem_mb = 16000,
    shell:
        """
        Rscript ~/tools/Pantry/Pheast/scripts/covariates.R \
            {input.vcf} \
            {input.bed} \
            {params.n_geno_pcs} \
            {params.n_pheno_pcs} \
            {output}
        """

######################
## Genetic analysis ##
######################

rule tensorqtl_perm:
    """Map cis-QTLs, determining significance using permutations.
    Outputs the top association per phenotype.
    """
    input:
        geno = multiext(geno_prefix, '.bed', '.bim', '.fam'),
        bed = 'qtl/latent-{param}.bed.gz',
        bedi = 'qtl/latent-{param}.bed.gz.tbi',
        covar = 'covar/latent-{param}.covar.tsv',
        groups = 'qtl/latent-{param}.phenotype_groups.txt',
    output:
        qtl = 'qtl/latent-{param}.cis_qtl.txt.gz',
    params:
        geno_prefix = geno_prefix,
    resources:
        walltime = 12,
        mem_mb = 16000,
        partition_etc = '--account=gpu-gdml-investor --partition=gpu-gdml-investor --gres=gpu:1',
    shell:
        """
        python ~/tools/Pantry/Pheast/scripts/run_tensorqtl.py \
            {params.geno_prefix} \
            {input.bed} \
            {output.qtl} \
            --covariates {input.covar} \
            --groups {input.groups} \
            --mode cis
        """

rule tensorqtl_independent:
    """Use stepwise regression to identify multiple conditionally independent cis-QTLs per phenotype."""
    input:
        geno = multiext(geno_prefix, '.bed', '.bim', '.fam'),
        bed = 'qtl/latent-{param}.bed.gz',
        bedi = 'qtl/latent-{param}.bed.gz.tbi',
        covar = 'covar/latent-{param}.covar.tsv',
        groups = 'qtl/latent-{param}.phenotype_groups.txt',
        cis = 'qtl/latent-{param}.cis_qtl.txt.gz',
    output:
        qtl = 'qtl/latent-{param}.cis_independent_qtl.txt.gz',
    params:
        geno_prefix = geno_prefix,
    resources:
        walltime = 20,
        mem_mb = 16000,
        partition_etc = '--account=gpu-gdml-investor --partition=gpu-gdml-investor --gres=gpu:1',
    shell:
        """
        python ~/tools/Pantry/Pheast/scripts/run_tensorqtl.py \
            {params.geno_prefix} \
            {input.bed} \
            {output.qtl} \
            --covariates {input.covar} \
            --cis_output {input.cis} \
            --groups {input.groups} \
            --mode cis_independent
        """

###########
## Stats ##
###########

rule count_bins_phenos_qtls:
    """Count the number of bins, phenotypes, and QTLs for each binning and model setting."""
    input:
        bins = expand('{param}/gene_bins/batch_{batch}.bed.gz', param=params, batch=range(N_BATCHES)),
        phenos = expand('{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz', param=params),
        phenos_tested = expand('qtl/latent-{param}.phenotype_groups.txt', param=params),
        qtls = expand('qtl/latent-{param}.cis_independent_qtl.txt.gz', param=params),
    output:
        tsv = 'bin_pheno_qtl_counts.tsv',
    params:
        params = params,
    shell:
        """
        echo -e "type\tparam\tn_bins\tn_phenos\tn_phenos_tested\tn_qtls" > {output.tsv}
        for param in {params.params}; do
            type=$(echo $param | cut -d- -f1)
            par=$(echo $param | cut -d- -f2)
            n_bins=$(zcat $param/gene_bins/batch_*.bed.gz | wc -l)
            n_phenos=$(zcat $param/phenotypes/latent_phenos.Geuvadis.tsv.gz | tail -n+2 | wc -l)
            n_phenos_tested=$(cat qtl/latent-$param.phenotype_groups.txt | wc -l)
            n_qtls=$(zcat qtl/latent-$param.cis_independent_qtl.txt.gz | tail -n+2 | wc -l)
            echo -e "$type\t$par\t$n_bins\t$n_phenos\t$n_phenos_tested\t$n_qtls" >> {output.tsv}
        done
        """
