"""Compare LaDDR results from different parameter settings"""

from pathlib import Path

BATCH_FILE = Path(f'trial0/binning-n_4/info/n_batches.txt')
assert BATCH_FILE.exists(), f'{BATCH_FILE} not found. Run laddr setup first.'
with open(BATCH_FILE, 'r') as f:
    N_BATCHES = int(f.read())

## awk '$1 ~ /^#!/ || $1 == "chr7"' ../../ref/human-ensembl/Homo_sapiens.GRCh38.113.chr.chrom.gtf > Homo_sapiens.GRCh38.113.chr.chrom.chr7.gtf
ref_anno = 'Homo_sapiens.GRCh38.113.chr.chrom.chr7.gtf'
geno_prefix = '../data/geuvadis/geno/GEUVADIS.445_samples.GRCh38.20170504.maf01.filtered.nodup.chr1-22'

binnings = []
for min_covg in [16, 32, 64, 128]:
    for max_corr in [0.8, 0.9, 0.95]:
        if (min_covg, max_corr) in [(16, 0.95), (32, 0.95)]:
            continue  # Too large
        binnings.append(f'a1_{min_covg}_{max_corr}')
for bins_per_gene in [128, 256, 384, 512, 768, 1024]:
    binnings.append(f'a2_{bins_per_gene}')
for bins_per_gene in [128, 256, 384, 512, 768, 1024]:
    binnings.append(f'a3_{bins_per_gene}')
for n in [4, 8, 12, 16, 24, 32]:
    binnings.append(f'n_{n}')
for w in [16, 32, 64]:
    binnings.append(f'w_{w}_{w * 8}')

models = []
for n in [6, 8, 10, 12, 14, 16, 20, 24]:
    models.append(f'pca_n{n}')
models += ['fpca_xpos_disc', 'fpca_xpos_spline', 'fpca_xbin_spline']

params = [f'binning-{x}' for x in binnings] + [f'model-{x}' for x in models]
trials = [f'trial{i}' for i in range(3)]

localrules:
    latent_pheno_groups,

rule all:
    input:
        # expand('{trial}/binning-{binning}/gene_bins/batch_{batch}.bed.gz', trial=trials, binning=['n_4'], batch=range(N_BATCHES)),
        # expand('{trial}/binning-{binning}/covg_norm/Geuvadis/batch_{batch}.npy', trial=trials, binning=['n_4'], batch=range(N_BATCHES)),
        # expand('{trial}/{param}/models/models_batch_{batch}.pickle', trial=trials, param=['binning-n_4'], batch=range(N_BATCHES)),
        expand('{trial}/binning-{binning}/phenotypes/latent_phenos.Geuvadis.tsv.gz', trial=trials, binning=binnings),
        # expand('{trial}/{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz', trial=trials, param=params),
        # expand('{trial}/qtl/latent-{param}.bed.gz', trial=trials, param=params),
        # expand('{trial}/qtl/latent-{param}.cis_independent_qtl.txt.gz', trial=trials, param=params),
        # 'bin_pheno_qtl_counts.tsv',

rule latent_rna_binning:
    """Divide gene features into bins"""
    input:
        genes = '{trial}/{param}/info/genes.tsv',
        exons = '{trial}/{param}/info/exons.tsv.gz',
        # bw = sample_table['path'].tolist(),
    output:
        beds = '{trial}/{param}/gene_bins/batch_{batch}.bed.gz',
    params:
        project_dir = '{trial}/{param}',
    resources:
        mem_mb = 32000,
        runtime = '24h',
    shell:
        """
        laddr binning -p {params.project_dir} -b {wildcards.batch}
        """

rule latent_rna_coverage:
    """Assemble coverage across samples, normalize, regress out explicit phenotypes, and bin into batches for PCA"""
    input:
        # bw = lambda w: sample_table.loc[sample_table['dataset'] == w.dataset, 'path'].tolist(),
        bins = '{trial}/{param}/gene_bins/batch_{batch}.bed.gz',
        median_covg = '{trial}/{param}/info/median_coverage.txt',
    output:
        covg = '{trial}/{param}/covg_norm/Geuvadis/batch_{batch}.npy',
        covg_norm_bins = '{trial}/{param}/covg_norm/Geuvadis/batch_{batch}.bins.tsv.gz',
    params:
        project_dir = '{trial}/{param}',
    resources:
        mem_mb = 32000,
        runtime = '24h',
    shell:
        """
        laddr coverage -p {params.project_dir} -b {wildcards.batch}
        """

rule latent_rna_fit:
    """Fit models to latent features"""
    input:
        covg_norm = '{trial}/{param}/covg_norm/Geuvadis/batch_{batch}.npy',
        covg_norm_bins = '{trial}/{param}/covg_norm/Geuvadis/batch_{batch}.bins.tsv.gz',
    output:
        models = '{trial}/{param}/models/models_batch_{batch}.pickle',
    params:
        project_dir = '{trial}/{param}',
    resources:
        mem_mb = 16000,
    shell:
        """
        laddr fit -p {params.project_dir} -b {wildcards.batch}
        """

rule latent_rna_transform:
    """Apply models to generate latent phenotypes"""
    input:
        covg_norm = expand('{{trial}}/{{param}}/covg_norm/Geuvadis/batch_{batch}.npy', batch=range(N_BATCHES)),
        covg_norm_bins = expand('{{trial}}/{{param}}/covg_norm/Geuvadis/batch_{batch}.bins.tsv.gz', batch=range(N_BATCHES)),
        models = expand('{{trial}}/{{param}}/models/models_batch_{batch}.pickle', batch=range(N_BATCHES)),
    output:
        phenos = '{trial}/{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz',
    params:
        project_dir = '{trial}/{param}',
    shell:
        """
        laddr transform -p {params.project_dir}
        """

##################################
## Genetic analysis preparation ##
##################################

rule assemble_latent_bed:
    """Add gene info to latent phenotypes to generate BED file"""
    input:
        phenos = '{trial}/{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz',
        ref_anno = ref_anno,
    output:
        bed = '{trial}/qtl/latent-{param}.unnorm.bed',
    params:
        qtl_dir = '{trial}/qtl',
    resources:
        mem_mb = 16000,
    shell:
        """
        mkdir -p {params.qtl_dir}
        python3 ~/tools/Pantry/phenotyping/scripts/assemble_bed.py \
            --type latent \
            --input {input.phenos} \
            --ref_anno {input.ref_anno} \
            --output {output.bed}
        """

rule normalize_latent:
    """Quantile-normalize values for QTL mapping"""
    input:
        bed = '{trial}/qtl/latent-{param}.unnorm.bed',
    output:
        bed = '{trial}/qtl/latent-{param}.bed.gz',
    params:
        bed = '{trial}/qtl/latent-{param}.bed',
    resources:
        mem_mb = 16000,
    shell:
        """
        python3 ~/tools/Pantry/phenotyping/scripts/normalize_phenotypes.py \
            --input {input.bed} \
            --output {params.bed}
        bgzip {params.bed}
        """

rule index_bed:
    """Index a BED file."""
    input:
        bed = '{trial}/qtl/latent-{param}.bed.gz',
    output:
        index = '{trial}/qtl/latent-{param}.bed.gz.tbi'
    shell:
        'tabix {input.bed}'

rule latent_pheno_groups:
    """Group phenotypes by gene for tensorQTL"""
    input:
        bed = '{trial}/qtl/latent-{param}.bed.gz',
    output:
        groups = '{trial}/qtl/latent-{param}.phenotype_groups.txt',
    shell:
        """
        zcat < {input} \
            | tail -n +2 \
            | cut -f4 \
            | awk '{{ g=$1; sub(/__.*$/, "", g); print $1 "\t" g }}' \
            > {output.groups}
        """

rule prune_for_covar:
    """Prune genotypes to compute covariate PCs.
    --indep-pairwise parameters are based on GTEx methods.
    """
    input:
        plink = multiext(geno_prefix, '.bed', '.bim', '.fam'),
    output:
        geno = multiext('{trial}/covar/geno_pruned', '.bed', '.bim', '.fam'),
    params:
        geno_prefix = geno_prefix,
        covar_dir = '{trial}/covar',
        pruned_prefix = '{trial}/covar/geno_pruned',
    shell:
        # --geno 0.05 filters variants with >5% missing values (the rest will be imputed).
        # Default is 0 so that samples with many more genotyped variants than others don't
        # result in other samples having mostly missing values after pruning.
        """
        mkdir -p {params.covar_dir}
        plink2 \
            --bfile {params.geno_prefix} \
            --geno 0.00 \
            --maf 0.05 \
            --indep-pairwise 200 100 0.1 \
            --out {params.pruned_prefix}
        plink2 \
            --bfile {params.geno_prefix} \
            --extract {params.pruned_prefix}.prune.in \
            --make-bed \
            --out {params.pruned_prefix}
        """

rule covariates:
    """Compute genotype and expression PCs and combine."""
    input:
        geno = multiext('{trial}/covar/geno_pruned', '.bed', '.bim', '.fam'),
        bed = '{trial}/qtl/latent-{param}.bed.gz',
    output:
        tsv = '{trial}/covar/latent-{param}.covar.tsv',
    params:
        pruned_prefix = '{trial}/covar/geno_pruned',
        n_geno_pcs = 5,
        n_pheno_pcs = 20,
    resources:
        mem_mb = 16000,
    shell:
        """
        Rscript ~/tools/Pantry/pheast/scripts/covariates.R \
            {params.pruned_prefix} \
            {input.bed} \
            {params.n_geno_pcs} \
            {params.n_pheno_pcs} \
            {output.tsv}
        """

######################
## Genetic analysis ##
######################

rule tensorqtl_cis:
    """Map cis-QTLs, determining significance using permutations.
    Outputs the top association per phenotype.
    """
    input:
        geno = multiext(geno_prefix, '.bed', '.bim', '.fam'),
        bed = '{trial}/qtl/latent-{param}.bed.gz',
        bedi = '{trial}/qtl/latent-{param}.bed.gz.tbi',
        covar = '{trial}/covar/latent-{param}.covar.tsv',
        groups = '{trial}/qtl/latent-{param}.phenotype_groups.txt',
    output:
        qtl = '{trial}/qtl/latent-{param}.cis_qtl.txt.gz',
    params:
        geno_prefix = geno_prefix,
    resources:
        mem_mb = 16000,
        # Define slurm_partition, slurm_account, and slurm_extra for GPU jobs as needed in the Snakemake profile config.yaml
    shell:
        """
        python ~/tools/Pantry/pheast/scripts/run_tensorqtl.py \
            {params.geno_prefix} \
            {input.bed} \
            {output.qtl} \
            --covariates {input.covar} \
            --groups {input.groups} \
            --mode cis
        """

rule tensorqtl_cis_independent:
    """Use stepwise regression to identify multiple conditionally independent cis-QTLs per phenotype."""
    input:
        geno = multiext(geno_prefix, '.bed', '.bim', '.fam'),
        bed = '{trial}/qtl/latent-{param}.bed.gz',
        bedi = '{trial}/qtl/latent-{param}.bed.gz.tbi',
        covar = '{trial}/covar/latent-{param}.covar.tsv',
        groups = '{trial}/qtl/latent-{param}.phenotype_groups.txt',
        cis = '{trial}/qtl/latent-{param}.cis_qtl.txt.gz',
    output:
        qtl = '{trial}/qtl/latent-{param}.cis_independent_qtl.txt.gz',
    params:
        geno_prefix = geno_prefix,
    resources:
        mem_mb = 16000,
        # Define slurm_partition, slurm_account, and slurm_extra for GPU jobs as needed in the Snakemake profile config.yaml
    shell:
        """
        python ~/tools/Pantry/pheast/scripts/run_tensorqtl.py \
            {params.geno_prefix} \
            {input.bed} \
            {output.qtl} \
            --covariates {input.covar} \
            --cis_output {input.cis} \
            --groups {input.groups} \
            --mode cis_independent
        """

###########
## Stats ##
###########

rule count_bins_phenos_qtls:
    """Count the number of bins, phenotypes, and QTLs for each binning and model setting."""
    input:
        bins = expand('{trial}/{param}/gene_bins/batch_{batch}.bed.gz', trial=trials, param=params, batch=range(N_BATCHES)),
        phenos = expand('{trial}/{param}/phenotypes/latent_phenos.Geuvadis.tsv.gz', trial=trials, param=params),
        phenos_tested = expand('{trial}/qtl/latent-{param}.phenotype_groups.txt', trial=trials, param=params),
        qtls = expand('{trial}/qtl/latent-{param}.cis_independent_qtl.txt.gz', trial=trials, param=params),
    output:
        tsv = 'bin_pheno_qtl_counts.tsv',
    params:
        params = params,
        trials = trials,
    shell:
        """
        echo -e "type\tparam\ttrial\tn_bins\tn_phenos\tn_phenos_tested\tn_qtls" > {output.tsv}
        for param in {params.params}; do
            type=$(echo $param | cut -d- -f1)
            par=$(echo $param | cut -d- -f2)
            for trial in {params.trials}; do
                n_bins=$(zcat $trial/$param/gene_bins/batch_*.bed.gz | wc -l)
                n_phenos=$(zcat $trial/$param/phenotypes/latent_phenos.Geuvadis.tsv.gz | tail -n+2 | wc -l)
                n_phenos_tested=$(cat $trial/qtl/latent-$param.phenotype_groups.txt | wc -l)
                n_qtls=$(zcat $trial/qtl/latent-$param.cis_independent_qtl.txt.gz | tail -n+2 | wc -l)
                echo -e "$type\t$par\t$trial\t$n_bins\t$n_phenos\t$n_phenos_tested\t$n_qtls" >> {output.tsv}
            done
        done
        """
